### ISSUE TITLE
Disable defenders from breaking blocks that attacker’s can’t break

### ISSUE THREAD

**Issue by wingsauce123** [StoneworksMC/War#12]
- **Please describe what you want in this suggestion.**
make it so defenders can’t break any blocks attackers can’t break 

This is to prevent gank and mole rp meta because you can’t rly mole when you can’t mine and no point building ganks when both sides are equally as strong in ganks.

(DEFENDERS WOULD STILL HAVE NORMAL BLOCK PLACING PERMS BTW)

**Comment by Matt-MX** [comment]
We'll be trying to balance out the playing field for both sides to turn the meta away from gross gank pits by allowing both sides to have similar perms, I think this is a duplicate issue so I'm gonna close it if you don't mind :)
